/*
 * New editor name:  tde, the Thomson-Davis Editor.
 * Author:           Frank Davis
 * Date:             June 5, 1991
 *
 */


struct screen macro_screen[] = {
 {1,0,"This utility reads an existing macro file.  The file must exist" },
 {2,0,"before running this utility.  If you create a few favorite macros" },
 {3,0,"in tde and save them to a file, you may use this utility to store" },
 {4,0,"them in tde.exe, so that those macros will be available each time" },
 {5,0,"you use tde."},
{10,20,"1. Install a macro file."},
{12,20,"2. Exit"},
{14,15,"Please enter your choice: "},
{0,0,NULL}
};
